### ISSUE TITLE
FlipClock counts down too fast

### ISSUE THREAD

**Issue by kireerik** [objectivehtml/FlipClock#258]
FlipClock counts down 2 times faster, than it should. Like: 9, 7, 5, 3, 1 ...

**Comment by kevinfilteau** [comment]
Same thing here, when I set a start time.

**Comment by aravindsrivats** [comment]
I can confirm. Happens only for a new Date() object.

**Comment by nishantrevur** [comment]
Happens even for the minute counter. The seconds countdown almost twice as fast than it should!

**Comment by ianisted** [comment]
I'm also getting this error.

**Comment by ianisted** [comment]
Thank you @aravindsrivats :)

**Comment by shoxter** [comment]
I'm getting this error as well for a normal 24 hour clock.

**Comment by danielsawan** [comment]
same bug here when setting a date. No bug when setting countdown in second instead of date object.

**Comment by premhameed** [comment]
var next_show = new Date('2018-12-01T00:00:00');
var diff = next_show.getTime() - new Date().getTime();
var showtime = Math.floor(diff/1000);
var clock = $('.clock').FlipClock({
    clockFace: 'DailyCounter',
    autoStart: false,
    showSeconds: false,
    countdown: true
});
clock.setTime(showtime);
clock.start();

showing wrong output

**Comment by bagzli** [comment]
Has this ever been resolved? I'm facing both issues listed here and can't use the library because of it.

**Comment by stewd** [comment]
Setting the countdown with the following creates the same error:

```js
var date = new Date("September 30, 2018 23:59:59");
var clock = $('.countdown').FlipClock(date,{
        clockFace: 'DailyCounter',
        countdown: true
    });
```

**The following displays correctly and count downs correctly, as it should.**

```js 
var timerDate   = "September 30, 2018 23:59:59"
var finaleDate  = new Date(timerDate);
var currentDate = new Date();
 var diff = finaleDate.getTime() / 1000 - currentDate.getTime() / 1000;
    if(diff < 0){
        diff = 0;
    }
    clock = $('.countdown').FlipClock(diff,{
        clockFace: 'DailyCounter',
        countdown: true,
    });
```

**Comment by objectivehtml** [comment]
This should be fixed in the latest v1 draft on the js-es6 branch. The library now uses requestAnimationFrame's to handle the timer and animations instead of intervals. Should improve performance and issues like this. In my latest tests, I have seen the clock skip 2 numbers when the GPU starts to lag and catches up. Previously it would just lag behind. Sometimes the browser is intensive and the animations fall behind. Also in the new version animation rate is now half of the interval rate by default. So it executes the animation faster, so it also reduces it lagging behind.

**Comment by lasrach** [comment]
Still broken in master for regular 24h flipclock and settting a non-Date value.

The bug is in compiled/flipclock.js:1348, function getDateObject:

it returns new Date().getTime() + this.getTimeSeconds()*1000, both of which are counting up.

**Comment by objectivehtml** [comment]
It not going to be fixed in master until I merge js-es6, which will happen in the next day or two. I have the new docs mostly finished, they are in the repo on the new branch if you want to check them out.
